import { Badge } from '@/components/ui/badge';

const tones: Record<string, string> = {
  pending: 'border-cabinet-warning/20 bg-cabinet-accent-soft text-cabinet-warning',
  pending_review: 'border-cabinet-warning/20 bg-cabinet-accent-soft text-cabinet-warning',
  account_created: 'border-cabinet-border bg-cabinet-panel-muted text-cabinet-muted-ink',
  kyb_in_progress: 'border-cabinet-warning/20 bg-cabinet-accent-soft text-cabinet-warning',
  kyb_under_review: 'border-cabinet-warning/20 bg-cabinet-accent-soft text-cabinet-warning',
  ready_for_review: 'border-cabinet-warning/20 bg-cabinet-accent-soft text-cabinet-warning',
  ready: 'border-cabinet-warning/20 bg-cabinet-accent-soft text-cabinet-warning',
  approved: 'border-cabinet-accent/15 bg-cabinet-accent-soft text-cabinet-accent-strong',
  approved_for_payout: 'border-cabinet-accent/15 bg-cabinet-accent-soft text-cabinet-accent-strong',
  posted: 'border-cabinet-accent/15 bg-cabinet-accent-soft text-cabinet-accent-strong',
  confirmed: 'border-cabinet-success/15 bg-emerald-50 text-cabinet-success',
  verified: 'border-cabinet-success/15 bg-emerald-50 text-cabinet-success',
  published: 'border-cabinet-success/15 bg-emerald-50 text-cabinet-success',
  live: 'border-cabinet-success/15 bg-emerald-50 text-cabinet-success',
  paid: 'border-cabinet-success/15 bg-emerald-50 text-cabinet-success',
  succeeded: 'border-cabinet-success/15 bg-emerald-50 text-cabinet-success',
  active: 'border-cabinet-success/15 bg-emerald-50 text-cabinet-success',
  processing: 'border-cabinet-ink/10 bg-cabinet-panel-muted text-cabinet-ink',
  pending_payout: 'border-cabinet-ink/10 bg-cabinet-panel-muted text-cabinet-ink',
  draft: 'border-cabinet-border bg-cabinet-panel-muted text-cabinet-muted-ink',
  fully_allocated: 'border-cabinet-accent/15 bg-cabinet-accent-soft text-cabinet-accent-strong',
  closed: 'border-cabinet-border bg-cabinet-panel-muted text-cabinet-muted-ink',
  manual_required: 'border-amber-200 bg-amber-50 text-amber-700',
  cancelled: 'border-cabinet-border bg-cabinet-panel-muted text-cabinet-muted-ink',
  failed: 'border-rose-200 bg-rose-50 text-rose-700',
  rejected: 'border-rose-200 bg-rose-50 text-rose-700',
  voided: 'border-rose-200 bg-rose-50 text-rose-700',
};

const labels: Record<string, string> = {
  pending: 'Ожидает действия',
  pending_review: 'На проверке',
  account_created: 'Аккаунт создан',
  kyb_in_progress: 'Идет проверка данных',
  kyb_under_review: 'На проверке',
  ready_for_review: 'Реквизиты готовы',
  ready: 'Готово к запуску',
  approved: 'Одобрено',
  approved_for_payout: 'Готово к выплате',
  confirmed: 'Подтверждено',
  draft: 'Черновик',
  published: 'Опубликовано',
  live: 'Идет сбор',
  active: 'Активно',
  rejected: 'Отклонено',
  cancelled: 'Отменено',
  paid: 'Выплачено',
  posted: 'Проведено',
  succeeded: 'Успешно',
  failed: 'Ошибка',
  processing: 'В обработке',
  pending_payout: 'Готовится к выплате',
  fully_allocated: 'Раунд заполнен',
  closed: 'Закрыто',
  manual_required: 'Нужна ручная выплата',
  verified: 'Подтверждено',
  voided: 'Аннулировано',
};

export function StatusBadge({ status }: { status: string }) {
  return <Badge className={tones[status] ?? tones.draft}>{labels[status] ?? status}</Badge>;
}
